# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for TyK Notebook Application
Generated by build_app.py
"""

block_cipher = None

a = Analysis(
    ['/home/jp/code/tyk/tyk_nb_local/tyk_app_entry.py'],
    pathex=['/home/jp/code/tyk/tyk_nb_local'],
    binaries=[],
    datas=[
        ('/home/jp/code/tyk/tyk_nb_local/tyk_notebook_app/templates', 'tyk_notebook_app/templates'),
        ('/home/jp/code/tyk/tyk_nb_local/tyk_notebook_app/migrations', 'tyk_notebook_app/migrations')
    ],
    hiddenimports=[
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.template.backends.django',
        'django.db.backends.sqlite3',
        'tyk_notebook_app',
        'tyk_notebook_app.models',
        'tyk_notebook_app.views',
        'tyk_notebook_app.admin',
        'tyk_notebook_app.urls',
        'tyk_notebook_app.urls_main',
        'tyk_notebook_app.executor',
        'tyk_notebook_app.importer',
        'tyk_notebook_app.parser',
        'pandas',
        'numpy',
        'plotly',
        'plotly.graph_objs',
        'plotly.io',
        'networkx',
        'matplotlib',
        'matplotlib.pyplot'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='tyk-notebook',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
