#!/usr/bin/env python
"""
TyK Notebook Application - Single-Click Launcher

This script provides a complete, self-contained launcher for the TyK Notebook application.
It handles:
- Django configuration
- Database setup and migrations
- Automatic notebook import
- Admin user creation
- Server startup
- Browser launch

Usage:
    python launcher.py [--port PORT] [--no-browser] [--reset-db]

Options:
    --port PORT      Port to run the server on (default: 8000)
    --no-browser     Don't automatically open browser
    --reset-db       Reset the database (delete existing data)
    --data-path PATH Path to TyK data directory
"""

import os
import sys
import argparse
import webbrowser
import threading
import time
from pathlib import Path

# Determine the base directory
BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent

# Add paths
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(BASE_DIR))

# Django settings module
SETTINGS_MODULE = "tyk_notebook_app.settings"


def configure_django():
    """Configure Django settings"""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", SETTINGS_MODULE)

    import django

    django.setup()


def create_settings_module():
    """Create the Django settings module if it doesn't exist"""
    settings_path = BASE_DIR / "settings.py"

    if not settings_path.exists():
        settings_content = generate_settings()
        with open(settings_path, "w") as f:
            f.write(settings_content)
        print(f"Created settings at {settings_path}")


def generate_settings():
    """Generate Django settings content"""
    return '''"""
Django settings for TyK Notebook Application.
Auto-generated by launcher.py
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent

SECRET_KEY = 'tyk-notebook-dev-key-change-in-production-' + os.urandom(16).hex()

DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tyk_notebook_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tyk_notebook_app.urls_main'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TyK specific settings
TYK_DATA_PATH = os.environ.get('TYK_DATA_PATH', str(PROJECT_ROOT))
'''


def create_main_urls():
    """Create the main URLs module"""
    urls_path = BASE_DIR / "urls_main.py"

    if not urls_path.exists():
        urls_content = '''"""
Main URL configuration for TyK Notebook Application.
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tyk_notebook_app.urls')),
]
'''
        with open(urls_path, "w") as f:
            f.write(urls_content)
        print(f"Created URLs at {urls_path}")


def setup_database(reset=False):
    """Set up the database"""
    from django.core.management import call_command

    db_path = BASE_DIR / "db.sqlite3"
    migrations_dir = BASE_DIR / "migrations"

    if reset:
        if db_path.exists():
            os.remove(db_path)
            print("Database reset.")
        # Also remove migrations to start fresh
        if migrations_dir.exists():
            import shutil

            shutil.rmtree(migrations_dir)
            print("Migrations cleared.")

    # Ensure migrations directory exists
    if not migrations_dir.exists():
        migrations_dir.mkdir(parents=True)
        (migrations_dir / "__init__.py").touch()

    print("Creating migrations...")
    call_command("makemigrations", "tyk_notebook_app", verbosity=0)

    print("Running migrations...")
    call_command("migrate", verbosity=0)
    print("Migrations complete.")


def create_admin_user():
    """Create admin user if it doesn't exist"""
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin", email="admin@localhost", password="admin"
        )
        print("Created admin user (username: admin, password: admin)")
    else:
        print("Admin user already exists.")


def import_demo_notebook(data_path=None):
    """Import the TyK demo notebook"""
    from tyk_notebook_app.models import Notebook

    if Notebook.objects.filter(slug="pruebaTyK").exists():
        print("Demo notebook already imported.")
        return

    from tyk_notebook_app.importer import import_notebook
    from tyk_notebook_app.parser import ColabNotebookParser

    # Find the demo file
    search_paths = [
        # PROJECT_ROOT / 'tyk_demo_20251018.py',
        # PROJECT_ROOT / 'tyk_demo_20251018.ipynb',
        PROJECT_ROOT / "pruebatyk.py",
        PROJECT_ROOT / "PruebaTYK.ipynb",
    ]

    if data_path:
        search_paths.insert(0, Path(data_path) / "pruebatyk.py")
        search_paths.insert(0, Path(data_path) / "PruebaTYK.ipynb")
        # search_paths.insert(0, Path(data_path) / "tyk_demo_20251018.py")
        # search_paths.insert(0, Path(data_path) / "tyk_demo_20251018.ipynb")

    demo_file = None
    for path in search_paths:
        if path.exists():
            demo_file = path
            break

    if demo_file:
        try:
            notebook = import_notebook(
                filepath=str(demo_file),
                # name="TyK Demo - October 2025",
                name="Prueba TyK 2026",
                description="Interactive TyK analysis and visualization demo. "
                "Explore clusters, networks, and bibliometric data.",
            )
            print(
                f"Imported notebook: {notebook.name} ({notebook.cells.count()} cells)"
            )
        except Exception as e:
            print(f"Warning: Could not import demo notebook: {e}")
    else:
        print(
            "No demo notebook found. You can import notebooks via the admin interface."
        )


def open_browser(port):
    """Open browser after a short delay"""
    url = f"http://localhost:{port}/"
    print(f"Opening browser at {url}")
    time.sleep(1.5)
    webbrowser.open(url)


def run_server(port=8000, open_browser_flag=True):
    """Run the development server"""
    from django.core.management import call_command

    if open_browser_flag:
        browser_thread = threading.Thread(target=open_browser, args=(port,))
        browser_thread.daemon = True
        browser_thread.start()

    print(f"\nStarting TyK Notebook server on http://localhost:{port}/")
    print("Press Ctrl+C to stop.\n")
    print("=" * 50)
    print(f"  Web Interface: http://localhost:{port}/")
    print(f"  Admin Panel:   http://localhost:{port}/admin/")
    print("  Credentials:   admin / admin")
    print("=" * 50)
    print()

    call_command("runserver", f"0.0.0.0:{port}", use_reloader=False)


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(description="TyK Notebook Application Launcher")
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to run the server on (default: 8000)",
    )
    parser.add_argument(
        "--no-browser", action="store_true", help="Don't automatically open browser"
    )
    parser.add_argument("--reset-db", action="store_true", help="Reset the database")
    parser.add_argument("--data-path", type=str, help="Path to TyK data directory")

    args = parser.parse_args()

    print("=" * 50)
    print("  TyK Notebook Application")
    print("=" * 50)
    print()

    # Set data path environment variable
    if args.data_path:
        os.environ["TYK_DATA_PATH"] = args.data_path

    # Create necessary files
    print("Setting up application...")
    create_settings_module()
    create_main_urls()

    # Configure Django
    configure_django()

    # Setup database
    setup_database(reset=args.reset_db)

    # Create admin user
    create_admin_user()

    # Import demo notebook
    import_demo_notebook(data_path=args.data_path)

    # Run server
    run_server(port=args.port, open_browser_flag=not args.no_browser)


if __name__ == "__main__":
    main()
