# Generated by Django 5.2.8 on 2026-01-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('cell_type', models.CharField(choices=[('code', 'Code'), ('markdown', 'Markdown'), ('setup', 'Setup (runs once)')], default='code', max_length=20)),
                ('source_code', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Markdown description shown above the cell')),
                ('is_executable', models.BooleanField(default=True)),
                ('auto_run', models.BooleanField(default=False, help_text='Run automatically when parameters change')),
                ('is_setup_cell', models.BooleanField(default=False, help_text='Run once at notebook initialization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='Parameter values used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('output_text', models.TextField(blank=True)),
                ('output_html', models.TextField(blank=True, help_text='HTML output (plots, tables)')),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tyk_notebook_app.cell')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='tyk_notebook_app.notebook'),
        ),
        migrations.CreateModel(
            name='NotebookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('kernel_state', models.JSONField(default=dict, help_text='Serialized kernel variables')),
                ('parameter_values', models.JSONField(default=dict, help_text='Current parameter values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tyk_notebook_app.cell')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tyk_notebook_app.notebook')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('notebook', 'order')},
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('param_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('string', 'Text Input'), ('number', 'Number'), ('boolean', 'Checkbox'), ('slider', 'Slider')], default='string', max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown type')),
                ('min_value', models.FloatField(blank=True, help_text='Min value for number/slider', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Max value for number/slider', null=True)),
                ('step', models.FloatField(blank=True, help_text='Step for slider', null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tyk_notebook_app.cell')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('cell', 'name')},
            },
        ),
    ]
