# Generated by Django 6.0.1 on 2026-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='source_code',
            field=models.TextField(blank=True, help_text='Source code (required for code cells, optional for markdown)'),
        ),
    ]
