# Generated by Django 6.0.1 on 2026-01-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0002_alter_cell_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown content shown above the cell'),
        ),
    ]
