# Generated by Django 6.0.1 on 2026-01-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0004_alter_notebooksession_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('world_map', 'Global Publications Map'), ('clusters_network', 'TOP Clusters Network'), ('subclusters_network', 'Subclusters Network'), ('cooc_network', 'Co-occurrence Network'), ('cluster_stats', 'Cluster Statistics')], max_length=50)),
                ('title', models.CharField(blank=True, help_text='Custom title (leave blank for default)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in dashboard')),
                ('is_active', models.BooleanField(default=True)),
                ('default_params', models.JSONField(blank=True, default=dict, help_text='Default parameters (e.g., colorscale, node_type, max_nodes)')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_charts', to='tyk_notebook_app.notebook')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('notebook', 'chart_type')},
            },
        ),
    ]
