# Generated by Django 6.0.1 on 2026-03-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0006_charttype_and_migrate_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChartParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, help_text='Display label (defaults to name if blank)', max_length=200)),
                ('param_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('string', 'Text Input'), ('number', 'Number'), ('boolean', 'Checkbox'), ('slider', 'Slider')], default='string', max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for dropdown type')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('step', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dashboard_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='tyk_notebook_app.dashboardchart')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('dashboard_chart', 'name')},
            },
        ),
    ]
