# Generated by Django 6.0.1 on 2026-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0007_add_dashboard_chart_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this cell in the notebook/dashboard view'),
        ),
    ]
