# Generated by Django 6.0.1 on 2026-07-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyk_notebook_app', '0010_notebook_dataset_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='overview_enabled',
            field=models.BooleanField(default=True, help_text='Show the Overview button/page for this notebook'),
        ),
    ]
